// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: myService.proto

package server

import (
	"context"

	"go-grpc-http-template/internal/logic/myservice"
	"go-grpc-http-template/internal/svc"
	"go-grpc-http-template/myService"
)

type MyServiceServer struct {
	svcCtx *svc.ServiceContext
	myService.UnimplementedMyServiceServer
}

func NewMyServiceServer(svcCtx *svc.ServiceContext) *MyServiceServer {
	return &MyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MyServiceServer) Health(ctx context.Context, in *myService.Request) (*myService.Response, error) {
	l := myservicelogic.NewHealthLogic(ctx, s.svcCtx)
	return l.Health(in)
}
