// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: myService.proto

package myservice

import (
	"context"

	"go-grpc-http-template/myService"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = myService.Request
	Response = myService.Response

	MyService interface {
		Health(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultMyService struct {
		cli zrpc.Client
	}
)

func NewMyService(cli zrpc.Client) MyService {
	return &defaultMyService{
		cli: cli,
	}
}

func (m *defaultMyService) Health(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := myService.NewMyServiceClient(m.cli.Conn())
	return client.Health(ctx, in, opts...)
}
